volumes:
  server_node_modules:

services:
  server:
    build:
      context: ./server
    container_name: server
    volumes:
      - ./server:/app
      - ./lib:/app/lib
      - server_node_modules:/app/node_modules
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
