volumes:
  server_node_modules:
services:
  server:
    build:
      context: ./server
    container_name: server
    volumes:
      - ./server:/app
      - ./lib:/app/lib
      - server_node_modules:/app/node_modules
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env

  db:
    image: mongo:6
    restart: always
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./db_data/:/data/db/
      - /etc/timezone:/etc/timezone:ro

  mongo-express:
    image: mongo-express
    restart: always
    container_name: db_ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example